package codegen

import (
	"strings"

	"github.com/llir/llvm/ir"
)

// registerBuiltinFuncs binds Koda global names to runtime LLVM symbols for native emission.
func (g *Generator) registerBuiltinFuncs() {
	pairs := []struct {
		name string
		fn   *ir.Func
	}{
		{"ok", g.runtimeOk},
		{"err", g.runtimeErr},
		{"panic", g.runtimePanic},
		{"assert", g.runtimeAssert},
		{"deltaTime", g.runtimeDeltaTime},
		{"print", g.runtimePrint},
		{"warn", g.runtimeWarn},
		{"len", g.runtimeLen},
		{"keys", g.runtimeKeys},
		{"type", g.runtimeType},
		{"typeof", g.runtimeType},
		{"matches", g.runtimeMatches},
		{"time", g.runtimeTime},
		{"clock", g.runtimeClock},
		{"timestamp", g.runtimeTimestamp},
		{"programTime", g.runtimeProgramTime},
		{"sleep", g.runtimeSleep},
		{"random", g.runtimeRandom},
		{"randomInt", g.runtimeRandomInt},
		{"randomChoice", g.runtimeRandomChoice},
		{"randomSeed", g.runtimeRandomSeed},
		{"lerp", g.runtimeLerp},
		{"clamp", g.runtimeClamp},
		{"distance", g.runtimeDistance},
		{"angleBetween", g.runtimeAngleBetween},
		{"map", g.runtimeMap},
		{"pi", g.runtimePI},
		{"e", g.runtimeE},
		{"sin", g.runtimeSin},
		{"cos", g.runtimeCos},
		{"tan", g.runtimeTan},
		{"asin", g.runtimeAsin},
		{"acos", g.runtimeAcos},
		{"atan", g.runtimeAtan},
		{"atan2", g.runtimeAtan2},
		{"pow", g.runtimePow},
		{"exp", g.runtimeExp},
		{"log", g.runtimeLog},
		{"log10", g.runtimeLog10},
		{"log2", g.runtimeLog2},
		{"floor", g.runtimeFloor},
		{"ceil", g.runtimeCeil},
		{"round", g.runtimeRound},
		{"trunc", g.runtimeTrunc},
		{"sign", g.runtimeSign},
		{"min", g.runtimeMin},
		{"max", g.runtimeMax},
		{"smoothstep", g.runtimeSmoothstep},
		{"distanceSq", g.runtimeDistanceSq},
		{"normalize", g.runtimeNormalize},
		{"hypot", g.runtimeHypot},
		{"fmod", g.runtimeFmod},
		{"degrees", g.runtimeDegrees},
		{"radians", g.runtimeRadians},
		{"wrap", g.runtimeWrap},
		{"approach", g.runtimeApproach},
		{"smoothdamp", g.runtimeSmoothdamp},
		{"isNumber", g.runtimeIsNumber},
		{"isString", g.runtimeIsString},
		{"isBool", g.runtimeIsBool},
		{"isNull", g.runtimeIsNull},
		{"isArray", g.runtimeIsArray},
		{"isObject", g.runtimeIsObject},
		{"isFunction", g.runtimeIsFunction},
		{"bool", g.runtimeBool},
		{"format", g.runtimeFormat},
		{"readFile", g.runtimeReadFile},
		{"writeFile", g.runtimeWriteFile},
		{"appendFile", g.runtimeAppendFile},
		{"fileExists", g.runtimeFileExists},
		{"deleteFile", g.runtimeDeleteFile},
		{"isFile", g.runtimeIsFile},
		{"isDir", g.runtimeIsDir},
		{"fileSize", g.runtimeFileSize},
		{"listDir", g.runtimeListDir},
		{"trace", g.runtimeTrace},
		{"parseJSON", g.runtimeParseJSON},
		{"toJSON", g.runtimeToJSON},
		{"abs", g.runtimeAbs},
		{"sqrt", g.runtimeSqrt},
		{"cbrt", g.runtimeCbrt},
		{"number", g.runtimeNumber},
		{"string", g.runtimeString},
		{"gc", g.runtimeGcCollect},
		{"gcCollect", g.runtimeGcCollect},
		{"gcDisable", g.runtimeGcDisable},
		{"gcEnable", g.runtimeGcEnable},
		{"gcFrameStep", g.runtimeGcFrameStep},
		{"gcStats", g.runtimeGcStats},
		{"internClear", g.runtimeInternClear},
		{"arena", g.runtimeArena},
		{"arenaReset", g.runtimeArenaReset},
		{"arenaAllocArray", g.runtimeArenaAllocArray},
		{"arenaAllocStruct", g.runtimeArenaAllocStruct},
		{"arraypush", g.runtimeArrayPushArgv},
		{"arraypop", g.runtimeArrayPopArgv},
		{"arrayslice", g.runtimeArraySlice},
		{"arraysort", g.runtimeArraySort},
		{"arrayreverse", g.runtimeArrayReverse},
		{"arrayincludes", g.runtimeArrayIncludes},
		{"arrayindexof", g.runtimeArrayIndexOf},
		{"arrayconcat", g.runtimeArrayConcat},
		{"assetpath", g.runtimeAssetPath},
		{"replace", g.runtimeStringReplace},
		{"replaceall", g.runtimeStringReplaceAll},
	}
	for _, p := range pairs {
		if p.fn != nil {
			g.funcs[strings.ToLower(p.name)] = p.fn
		}
	}
}
