package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// emitPackageArtifacts writes koda.json fragment, META.json, examples.md, and docs/.
func (wg *WrapperGenerator) emitPackageArtifacts(api *API) error {
	if err := os.MkdirAll(filepath.Join(wg.config.OutputDir, "docs"), 0755); err != nil {
		return err
	}
	if !wg.config.NoDocsMarkdown {
		if err := wg.emitExamples(api); err != nil {
			return err
		}
	}
	if err := wg.emitKodaJSON(api); err != nil {
		return err
	}
	if err := wg.emitMETA(api); err != nil {
		return err
	}
	return nil
}

func (wg *WrapperGenerator) linkFlagsString() string {
	parts := append([]string{}, wg.config.LinkFlags...)
	for _, d := range wg.config.IncludePaths {
		d = strings.TrimSpace(d)
		if d != "" {
			parts = append(parts, "-I"+d)
		}
	}
	if len(parts) == 0 {
		return fmt.Sprintf("-I<include-dir> -L<lib-dir> -l%s", apiNameOr(wg.config))
	}
	return strings.Join(parts, " ")
}

func apiNameOr(cfg *WrapGenConfig) string {
	if cfg.LibraryName != "" {
		return cfg.LibraryName
	}
	return "lib"
}

func (wg *WrapperGenerator) emitKodaJSON(api *API) error {
	path := filepath.Join(wg.config.OutputDir, "koda.json")
	frag := map[string]interface{}{
		"comment": fmt.Sprintf("Merge native section into your project koda.json for %s", api.Name),
		"native": map[string]string{
			"sources":   "wrapper.c",
			"linkflags": wg.linkFlagsString(),
		},
		"wrap": map[string]interface{}{
			"library":    api.Name,
			"import":     "@" + api.Name,
			"include":    fmt.Sprintf("#include \"@%s\"", api.Name),
			"headers":    api.Headers,
			"generated":  wg.config.GeneratedAt,
			"generator":  generatedByBrand,
			"version":    wg.config.Version,
		},
	}
	b, err := json.MarshalIndent(frag, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, b, 0644)
}

func (wg *WrapperGenerator) emitMETA(api *API) error {
	path := filepath.Join(wg.config.OutputDir, "META.json")
	meta := map[string]interface{}{
		"name":          api.Name,
		"generator":     generatedByBrand,
		"version":       wg.config.Version,
		"generated_at":  wg.config.GeneratedAt,
		"primary_header": wg.config.PrimaryHeader,
		"headers":       api.Headers,
		"counts": map[string]int{
			"functions": len(api.Functions),
			"structs":   len(api.Structs),
			"enums":     len(api.Enums),
			"constants": len(api.Constants),
		},
		"import":      "@" + api.Name,
		"linkflags":   wg.linkFlagsString(),
		"docs": map[string]string{
			"readme":        "README.md",
			"api_reference": "api_reference.md",
			"examples":      "examples.md",
			"html":          "docs/index.html",
		},
	}
	b, err := json.MarshalIndent(meta, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, b, 0644)
}

func (wg *WrapperGenerator) emitExamples(api *API) error {
	path := filepath.Join(wg.config.OutputDir, "examples.md")
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	q := func(s string, a ...interface{}) { fmt.Fprintf(f, s, a...) }

	q("# %s — examples\n\n", api.Name)
	q("Generated by **%s**. Copy into your project after linking `wrapper.c`.\n\n", generatedByBrand)
	q("```koda\n#include \"@%s\"\n\n", api.Name)
	q("func main() {\n")
	if ex := wg.pickExampleCall(api); ex != "" {
		q("    %s\n", ex)
	} else if len(api.Functions) > 0 {
		fn := api.Functions[0]
		q("    %s();\n", fn.Name)
	}
	q("}\n```\n\n")

	cats := groupFunctionsByCategory(api.Functions)
	keys := sortCategoryKeys(cats)
	for _, cat := range keys {
		q("## %s\n\n", cat)
		limit := 0
		for _, fn := range cats[cat] {
			if wg.skipGlueFunction(fn) {
				continue
			}
			if limit >= 5 {
				q("_…and %d more in [api_reference.md](api_reference.md)._\n\n", len(cats[cat])-limit)
				break
			}
			params := wg.bindingParamList(fn)
			if params != "" {
				q("```koda\n%s(%s);\n```\n\n", fn.Name, params)
			} else {
				q("```koda\n%s();\n```\n\n", fn.Name)
			}
			limit++
		}
	}
	return nil
}
