package main

import (
	"fmt"
	"html"
	"os"
	"path/filepath"
	"strings"
	"unicode"
	"unicode/utf8"
)

func titleDisplay(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return s
	}
	r, n := utf8.DecodeRuneInString(s)
	if r == utf8.RuneError {
		return s
	}
	return string(unicode.ToUpper(r)) + s[n:]
}

// emitProfessionalDocs writes README.md, api_reference.md, and index.html per project style.
func (wg *WrapperGenerator) emitProfessionalDocs(api *API) error {
	if !wg.config.NoDocsMarkdown {
		if err := wg.emitReadme(api); err != nil {
			return err
		}
		if err := wg.emitAPIReference(api); err != nil {
			return err
		}
	}
	if !wg.config.NoHTML {
		return wg.emitIndexHTML(api)
	}
	return nil
}

func (wg *WrapperGenerator) emitReadme(api *API) error {
	path := filepath.Join(wg.config.OutputDir, "README.md")
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	p := func(s string, a ...interface{}) { fmt.Fprintf(f, s, a...) }

	hdr := wg.config.PrimaryHeader
	if hdr == "" && len(api.Headers) > 0 {
		hdr = filepath.Base(api.Headers[0])
	}

	p("# %s Koda bindings\n\n", titleDisplay(api.Name))
	p("Auto-generated by **%s** %s from `%s`. **%d** functions wrapped", generatedByBrand, wg.config.Version, hdr, len(api.Functions))
	if len(api.Enums) > 0 {
		p(", **%d** enum types", len(api.Enums))
	}
	if len(wg.emitableMacros(api.Macros)) > 0 {
		p(", numeric **#define** constants")
	}
	p(".\n\n")

	p("## Quick start\n\n```koda\n")
	p("#include \"@%s\"\n\n", api.Name)
	p("func main() {\n")
	if ex := wg.pickExampleCall(api); ex != "" {
		p("    %s\n", ex)
	} else {
		p("    // Call library functions after linking wrapper.c\n")
	}
	p("}\n```\n\n")

	p("## Package layout\n\n")
	p("| File | Purpose |\n")
	p("|------|---------|\n")
	p("| `%s.koda` | Koda bindings |\n", api.Name)
	p("| `wrapper.c` | C glue linked via `KODA_NATIVE_SOURCES` |\n")
	p("| `koda.json` | Merge `native` section into your project |\n")
	p("| `META.json` | Machine-readable package metadata |\n")
	p("| `api_reference.md` | Full API |\n")
	p("| `examples.md` | Copy-paste examples |\n")
	p("| `docs/index.html` | Browsable offline docs |\n\n")

	p("## Building\n\n")
	link := wg.linkFlagsString()
	p("Link flags for this library (also in `koda.json`):\n\n```text\n%s\n```\n\n", link)
	p("```powershell\n")
	p("$env:KODA_NATIVE_SOURCES = \".\\wrapper.c\"\n")
	p("$env:KODA_LINKFLAGS = \"%s\"\n", link)
	p("koda build game.koda -o game.exe\n")
	p("```\n\n")
	p("```bash\n")
	p("export KODA_NATIVE_SOURCES=\"$PWD/wrapper.c\"\n")
	p("export KODA_LINKFLAGS=\"%s\"\n", link)
	p("koda build game.koda -o game\n")
	p("```\n\n")
	p("Set **`KODA_WRAPPERS`** to the parent folder to use `import \"@%s\"` without copying files.\n\n", api.Name)

	p("## Function categories\n\n")
	p("| Category | Count | Description |\n")
	p("|----------|-------|-------------|\n")
	cats := groupFunctionsByCategory(api.Functions)
	for _, name := range sortCategoryKeys(cats) {
		p("| %s | %d | Auto-grouped from name prefixes. |\n", name, len(cats[name]))
	}
	p("\n## Full API reference\n\n")
	p("- [api_reference.md](api_reference.md) — complete listing\n")
	p("- [examples.md](examples.md) — sample calls\n")
	p("- [docs/index.html](docs/index.html) — searchable browser docs\n\n")
	p("## License\n\nThese bindings are generated. The underlying **%s** library retains its own license — see the upstream header.\n", api.Name)
	return nil
}

func (wg *WrapperGenerator) pickExampleCall(api *API) string {
	for _, fn := range api.Functions {
		if fn.Name == "InitWindow" && len(fn.Parameters) >= 3 {
			return "InitWindow(800, 450, \"Hello\");"
		}
	}
	for _, fn := range api.Functions {
		if len(fn.Parameters) == 0 && strings.HasPrefix(fn.Name, "Get") {
			return fn.Name + "();"
		}
	}
	return ""
}

func (wg *WrapperGenerator) emitAPIReference(api *API) error {
	path := filepath.Join(wg.config.OutputDir, "api_reference.md")
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	q := func(s string, a ...interface{}) { fmt.Fprintf(f, s, a...) }

	hdr := wg.config.PrimaryHeader
	if hdr == "" && len(api.Headers) > 0 {
		hdr = filepath.Base(api.Headers[0])
	}

	q("# %s API reference\n\n", api.Name)
	q("> Generated by **%s** %s from `%s`. **%d** functions", generatedByBrand, wg.config.Version, hdr, len(api.Functions))
	if len(api.Enums) > 0 {
		q(", **%d** enums", len(api.Enums))
	}
	emitMacros := wg.emitableMacros(api.Macros)
	if len(emitMacros) > 0 {
		q(", **%d** macros", len(emitMacros))
	}
	q(".\n\n")

	if len(api.Enums) > 0 {
		q("## Enums\n\n")
		for _, enum := range api.Enums {
			if len(enum.Values) == 0 {
				continue
			}
			q("### `%s`\n\n", enum.Name)
			q("| Constant | Value |\n")
			q("|----------|-------|\n")
			for _, v := range enum.Values {
				if !isValidWrapgenBindingName(v.Name) {
					continue
				}
				q("| `%s` | %s |\n", v.Name, formatIntLiteral(v.Value))
			}
			q("\n")
		}
	}

	if len(emitMacros) > 0 {
		q("## Macros\n\n")
		q("| Name | Value |\n")
		q("|------|-------|\n")
		for _, m := range emitMacros {
			if v, ok := evaluateIntLiteral(strings.TrimSpace(m.Value)); ok {
				q("| `%s` | %s |\n", m.Name, formatIntLiteral(v))
			}
		}
		q("\n")
	}

	cats := groupFunctionsByCategory(api.Functions)
	keys := sortCategoryKeys(cats)

	q("## Table of contents\n\n")
	for _, c := range keys {
		q("- [%s](#%s)\n", c, anchorID(c))
	}
	q("\n")

	for _, cat := range keys {
		q("## %s\n\n", cat)
		for _, fn := range cats[cat] {
			if wg.skipGlueFunction(fn) {
				continue
			}
			desc := strings.TrimSpace(fn.Documentation)
			if desc == "" {
				desc = describeFromCamelName(fn.Name)
			}
			params := wg.bindingParamList(fn)
			ret := strings.TrimSpace(fn.ReturnType)
			ret = strings.TrimPrefix(ret, "RLAPI ")
			ret = strings.TrimSpace(ret)
			sig := fn.Name + "(" + params + ")"
			if ret != "" && ret != "void" {
				sig += " → " + kodaDocTypeForCType(ret)
			}

			q("### `%s`\n\n", fn.Name)
			q("```koda\n%s\n```\n\n", sig)
			q("%s\n\n", desc)

			if len(fn.Parameters) > 0 {
				q("**Parameters**\n\n")
				q("| Name | Type | Description |\n")
				q("|------|------|-------------|\n")
				for i, param := range fn.Parameters {
					nm := strings.TrimSpace(param.Name)
					if nm == "" {
						nm = fmt.Sprintf("arg%d", i)
					}
					ft, hint := paramDocLine(nm, param.Type)
					q("| %s | %s | %s |\n", nm, ft, hint)
				}
				q("\n")
			}
			if ret == "" || ret == "void" {
				q("**Returns:** nothing\n\n---\n\n")
			} else {
				q("**Returns:** %s\n\n---\n\n", kodaDocTypeForCType(ret))
			}
		}
	}
	return nil
}

func (wg *WrapperGenerator) emitIndexHTML(api *API) error {
	docsDir := filepath.Join(wg.config.OutputDir, "docs")
	if err := os.MkdirAll(docsDir, 0755); err != nil {
		return err
	}
	path := filepath.Join(docsDir, "index.html")
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	hdr := html.EscapeString(wg.config.PrimaryHeader)
	if hdr == "" && len(api.Headers) > 0 {
		hdr = html.EscapeString(filepath.Base(api.Headers[0]))
	}
	lib := html.EscapeString(api.Name)

	cats := groupFunctionsByCategory(api.Functions)
	keys := sortCategoryKeys(cats)

	var nav strings.Builder
	for _, c := range keys {
		id := anchorID(c)
		nav.WriteString(fmt.Sprintf(`<li><a href="#%s">%s (%d)</a></li>`+"\n", id, html.EscapeString(c), len(cats[c])))
	}

	var main strings.Builder
	for _, cat := range keys {
		cid := anchorID(cat)
		main.WriteString(fmt.Sprintf(`<section id="%s"><h2>%s</h2>`, cid, html.EscapeString(cat)) + "\n")
		for _, fn := range cats[cat] {
			if wg.skipGlueFunction(fn) {
				continue
			}
			desc := html.EscapeString(strings.TrimSpace(fn.Documentation))
			if desc == "" {
				desc = html.EscapeString(describeFromCamelName(fn.Name))
			}
			params := wg.bindingParamList(fn)
			sig := html.EscapeString(fn.Name + "(" + params + ")")
			main.WriteString(fmt.Sprintf(
				`<article class="fn" data-name="%s"><h3><code>%s</code></h3>`+
					`<pre class="sig"><code>%s</code></pre><p>%s</p>`,
				html.EscapeString(fn.Name), html.EscapeString(fn.Name), sig, desc))
			if len(fn.Parameters) > 0 {
				main.WriteString("<table><thead><tr><th>Name</th><th>Type</th></tr></thead><tbody>")
				for i, param := range fn.Parameters {
					nm := strings.TrimSpace(param.Name)
					if nm == "" {
						nm = fmt.Sprintf("arg%d", i)
					}
					ft := kodaDocTypeForCType(param.Type)
					main.WriteString(fmt.Sprintf("<tr><td>%s</td><td>%s</td></tr>",
						html.EscapeString(nm), html.EscapeString(ft)))
				}
				main.WriteString("</tbody></table>")
			}
			main.WriteString("</article>\n")
		}
		main.WriteString("</section>\n")
	}

	page := `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>` + lib + ` — Koda bindings</title>
<style>
:root {
  --bg:#f8fafc; --surface:#fff; --sidebar:#0f172a; --sidebar-text:#cbd5e1;
  --accent:#0ea5e9; --accent2:#f97316; --code:#f1f5f9; --text:#0f172a; --muted:#64748b;
  --border:#e2e8f0;
}
html[data-theme="dark"] {
  --bg:#0b1120; --surface:#111827; --code:#1e293b; --text:#f1f5f9; --muted:#94a3b8; --border:#334155;
}
* { box-sizing: border-box; }
body { margin:0; font-family: "Segoe UI", system-ui, sans-serif; background:var(--bg); color:var(--text); display:flex; min-height:100vh; line-height:1.5; }
nav.sidebar { width:280px; background:var(--sidebar); color:var(--sidebar-text); padding:1.25rem; flex-shrink:0; overflow-y:auto; }
nav.sidebar a { color:var(--sidebar-text); text-decoration:none; display:block; padding:0.2rem 0; }
nav.sidebar a:hover { color:var(--accent); }
nav .logo { font-weight:700; font-size:1.1rem; margin-bottom:0.25rem; color:#fff; }
nav .sub { font-size:0.8rem; color:#94a3b8; margin-bottom:1rem; }
#theme { margin-bottom:0.75rem; width:100%; padding:0.4rem; cursor:pointer; border-radius:8px; border:1px solid #334155; background:#1e293b; color:#e2e8f0; }
#search { width:100%; padding:0.55rem 0.75rem; border-radius:8px; border:none; margin-bottom:1rem; background:#1e293b; color:#f8fafc; }
nav ul { list-style:none; padding:0; margin:0; }
nav li { margin:0.15rem 0; }
main { flex:1; padding:2rem 2.5rem; max-width:960px; }
.hero { background:linear-gradient(135deg,#0ea5e9 0%,#6366f1 100%); color:#fff; padding:1.5rem; border-radius:12px; margin-bottom:2rem; }
.hero h1 { margin:0 0 0.5rem; font-size:1.75rem; }
.hero p { margin:0; opacity:0.95; }
section { margin-bottom:2.5rem; }
section h2 { font-size:1.25rem; border-bottom:2px solid var(--accent); padding-bottom:0.35rem; margin-bottom:1rem; }
.fn { margin-bottom:1.75rem; padding-bottom:1.25rem; border-bottom:1px solid var(--border); }
.fn h3 { margin:0 0 0.5rem; font-size:1rem; }
.fn h3 code { background:var(--code); padding:0.15rem 0.4rem; border-radius:4px; }
pre.sig { background:var(--code); padding:0.75rem 1rem; border-radius:8px; overflow:auto; position:relative; border:1px solid var(--border); margin:0.5rem 0; }
pre.sig code { font-family: Consolas, monospace; font-size:0.9rem; }
.fn p { color:var(--muted); margin:0.5rem 0; }
table { border-collapse:collapse; width:100%; margin-top:0.5rem; font-size:0.9rem; }
th, td { border:1px solid var(--border); padding:0.4rem 0.6rem; text-align:left; }
th { background:var(--code); }
button.copy { position:absolute; top:8px; right:8px; font-size:0.7rem; cursor:pointer; border-radius:6px; border:1px solid var(--border); background:var(--surface); padding:0.2rem 0.5rem; }
footer { margin-top:3rem; font-size:0.85rem; color:var(--muted); }
@media (max-width:800px) { body { flex-direction:column; } nav.sidebar { width:100%; } }
</style>
</head>
<body>
<nav class="sidebar">
  <div class="logo">Koda × ` + lib + `</div>
  <div class="sub">` + generatedByBrand + ` · offline API</div>
  <button type="button" id="theme" aria-label="Toggle theme">Toggle theme</button>
  <input type="search" id="search" placeholder="Search API…" autocomplete="off">
  <p><a href="../README.md">README</a> · <a href="../examples.md">Examples</a> · <a href="../api_reference.md">Markdown</a></p>
  <ul class="categories">` + nav.String() + `</ul>
</nav>
<main>
<div class="hero"><h1>` + lib + `</h1><p>` + fmt.Sprintf("%d", len(api.Functions)) + ` functions · Generated from ` + hdr + `</p></div>
` + main.String() + `
<footer>Generated by ` + generatedByBrand + `. Underlying library retains its own license.</footer>
</main>
<script>
(function(){
  var inp = document.getElementById('search');
  if (inp) inp.addEventListener('input', function() {
    var q = (inp.value || '').toLowerCase();
    document.querySelectorAll('.fn').forEach(function(el) {
      var n = (el.dataset.name || '').toLowerCase();
      el.style.display = (!q || n.indexOf(q) !== -1) ? '' : 'none';
    });
  });
  var th = document.getElementById('theme');
  if (th) th.addEventListener('click', function() {
    var h = document.documentElement;
    h.setAttribute('data-theme', h.getAttribute('data-theme') === 'dark' ? 'light' : 'dark');
  });
  document.querySelectorAll('pre.sig').forEach(function(pre) {
    var btn = document.createElement('button');
    btn.type = 'button'; btn.className = 'copy'; btn.textContent = 'Copy';
    btn.addEventListener('click', function() {
      var t = pre.querySelector('code'); if (!t) return;
      navigator.clipboard.writeText(t.textContent || '');
    });
    pre.appendChild(btn);
  });
})();
</script>
</body>
</html>`
	_, err = f.WriteString(page)
	return err
}
