// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbsFromWorkspace(arg1) {
  return window['go']['main']['App']['AbsFromWorkspace'](arg1);
}

export function BuildProgram(arg1, arg2, arg3) {
  return window['go']['main']['App']['BuildProgram'](arg1, arg2, arg3);
}

export function DefaultBuildOutput(arg1) {
  return window['go']['main']['App']['DefaultBuildOutput'](arg1);
}

export function DiagnoseFile(arg1, arg2) {
  return window['go']['main']['App']['DiagnoseFile'](arg1, arg2);
}

export function GetWorkspaceRoot() {
  return window['go']['main']['App']['GetWorkspaceRoot']();
}

export function LSPMessage(arg1) {
  return window['go']['main']['App']['LSPMessage'](arg1);
}

export function ListDir(arg1) {
  return window['go']['main']['App']['ListDir'](arg1);
}

export function OpenWorkspace(arg1) {
  return window['go']['main']['App']['OpenWorkspace'](arg1);
}

export function PickWorkspaceFolder() {
  return window['go']['main']['App']['PickWorkspaceFolder']();
}

export function PickParentFolderForNewProject() {
  return window['go']['main']['App']['PickParentFolderForNewProject']();
}

export function CreateProjectInParent(arg1, arg2) {
  return window['go']['main']['App']['CreateProjectInParent'](arg1, arg2);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RunProgram(arg1, arg2) {
  return window['go']['main']['App']['RunProgram'](arg1, arg2);
}

export function TerminalClose(arg1) {
  return window['go']['main']['App']['TerminalClose'](arg1);
}

export function TerminalResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['TerminalResize'](arg1, arg2, arg3);
}

export function TerminalStart(arg1, arg2) {
  return window['go']['main']['App']['TerminalStart'](arg1, arg2);
}

export function TerminalWrite(arg1, arg2) {
  return window['go']['main']['App']['TerminalWrite'](arg1, arg2);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
