// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {main} from '../models';

export function AbsFromWorkspace(arg1:string):Promise<string>;

export function BuildProgram(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DefaultBuildOutput(arg1:string):Promise<string>;

export function DiagnoseFile(arg1:string,arg2:string):Promise<Array<api.Diagnostic>>;

export function GetWorkspaceRoot():Promise<string>;

export function LSPMessage(arg1:string):Promise<string>;

export function ListDir(arg1:string):Promise<Array<main.DirEntry>>;

export function OpenWorkspace(arg1:string):Promise<void>;

export function PickWorkspaceFolder():Promise<string>;

export function PickParentFolderForNewProject():Promise<string>;

export function CreateProjectInParent(arg1:string,arg2:string):Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function RunProgram(arg1:string,arg2:string):Promise<void>;

export function TerminalClose(arg1:string):Promise<void>;

export function TerminalResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function TerminalStart(arg1:number,arg2:number):Promise<string>;

export function TerminalWrite(arg1:string,arg2:string):Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
